tool: exomiser
tool_version: 14.0.2
variant_analysis: True
gene_analysis: True
disease_analysis: False
tool_specific_configuration_options:
  environment: local
  exomiser_software_directory: exomiser-cli-14.0.2
  analysis_configuration_file: preset-exome-analysis.yml
  max_jobs: 0
  application_properties:
    remm_version:
    cadd_version:
    hg19_data_version: "2406"
    hg19_local_frequency_path:
    hg19_whitelist_path:
    hg38_data_version: "2406"
    hg38_local_frequency_path:
    hg38_whitelist_path:
    phenotype_data_version: "2406"
    cache_type: caffeine
    cache_caffeine_spec: 100000
  output_formats: [JSON]
  post_process:
    score_name: combinedScore
    sort_order: DESCENDING