benchmark_name: phenotype_only_benchmark
runs:
  - run_identifier: Exomiser
    results_dir: results/exomiser-14.0.2-2406/phenopacket_store_0.1.11_phenotypes
    phenopacket_dir: corpora/phenopacket_store_0.1.11_phenotypes/phenopackets
    gene_analysis: True
    variant_analysis: False
    disease_analysis: False
    threshold:
    score_order: descending
  - run_identifier: GADO
    results_dir: results/gado-1.0.4/phenopacket_store_0.1.11_phenotypes
    phenopacket_dir: corpora/phenopacket_store_0.1.11_phenotypes/phenopackets
    gene_analysis: True
    variant_analysis: False
    disease_analysis: False
    threshold:
    score_order: descending
  - run_identifier: PhenoGenius
    results_dir: results/phenogenius-1.1.1-2024-07-15/phenopacket_store_0.1.11_phenotypes
    phenopacket_dir: corpora/phenopacket_store_0.1.11_phenotypes/phenopackets
    gene_analysis: True
    variant_analysis: False
    disease_analysis: False
    threshold:
    score_order: descending
  - run_identifier: Phen2Gene
    results_dir: results/phen2gene-1.2.3/phenopacket_store_0.1.11_phenotypes
    phenopacket_dir: corpora/phenopacket_store_0.1.11_phenotypes/phenopackets
    gene_analysis: True
    variant_analysis: False
    disease_analysis: False
    threshold:
    score_order: descending
plot_customisation:
  gene_plots:
    plot_type: bar_cumulative
    rank_plot_title:
    roc_curve_title:
    precision_recall_title:
  disease_plots:
    plot_type: bar_cumulative
    rank_plot_title:
    roc_curve_title:
    precision_recall_title:
  variant_plots:
    plot_type: bar_cumulative
    rank_plot_title:
    roc_curve_title:
    precision_recall_title:
